Added tests for error messages and fixed a few issues exposed by that.

diff --git a/test/testhelper b/test/testhelper
--- a/test/testhelper
+++ b/test/testhelper
@@ -32,12 +32,32 @@
 # does report an issue, then the valgrind output is displayed and the
 # exit status is 1. In either case the actual output of Frobby is
 # ignored and is thus not compared to the correct reference output.
+#
+# If $4 is _expectExitCode, then the expected error code is $5 instead
+# of the usual expectation of 0.
+#
+# If $4 is _matchError, then the output written to standard error is
+# matched against the reference output, instead of that written to
+# standard out. Lines containing the word DEBUG is removed from this
+# output.
+#
+# These options can all be combined by adding them one after each
+# other, in which case the last setting of some options is used,
+# and then of course the options will be further along than $4.
 
 # This script is designed to be run from a sub-directory of where it
 # resides.
 
+printDebugOutput=0
 origParams="$*" # used for debug output below
-frobby=../../bin/frobby
+origFrobby="../../bin/frobby"
+origFrobbyOut="/tmp/frobbyTestScriptTemporary_standardOutput"
+origFrobbyErr="/tmp/frobbyTestScriptTemporary_standardError"
+frobbyChangedErr="/tmp/frobbyTestScriptTemporary_standardErrorChanged"
+
+frobby="$origFrobby"
+frobbyOut="$origFrobbyOut"
+frobbyErr="$origFrobbyErr"
 action="$1"
 inputFile="$2"
 referenceOutputFile="$3"
@@ -50,30 +70,59 @@ shift
 shift
 shift
 
-generate=0
-if [ "$1" = "_generate" ];
-then
-  generate=1;
-  shift;
-fi
+# Set initial values
+generate=0;
+expectedExitCode=0;
+matchErr=0;
+useValgrind=0;
+summary=0;
 
-summary=0
-if [ "$1" = "_summary" ];
-then
-  summary=1;
-  shift;
-fi
+changed=1;
+while [ $changed = 1 ];
+do
+  changed=0;
 
-valg=0
-if [ "$1" = "_valgrind" ];
-then
-  valg=1;
-  shift;
-fi
+  if [ "$1" = "_generate" ];
+  then
+    changed=1;
+    if [ "$inputFile" == "$referenceOutputFile" ]; then exit 0; fi
+    generate=1;
+    shift;
+  fi
+
+  if [ "$1" = "_summary" ];
+  then
+    changed=1;
+    summary=1;
+    shift;
+  fi
+
+  if [ "$1" = "_valgrind" ];
+  then
+    changed=1;
+    useValgrind=1;
+    frobby="valgrind $frobby"
+    shift;
+  fi
+
+  if [ "$1" = "_expectExitCode" ];
+  then
+    changed=1;
+    expectedExitCode="$2";
+    shift;
+    shift;
+  fi
+
+  if [ "$1" = "_matchError" ];
+  then
+    changed=1;
+    matchErr=1;
+    shift;
+  fi
+done
 
 params="$*"
 
-printDebugOutput=0
 if [ "$printDebugOutput" == 1 ];
 then
   echo "------ debug output ------"
@@ -83,42 +132,70 @@ then
   echo "inputFile is \"$inputFile\""
   echo "params is \"$params\""
   echo "referenceOutputFile is \"$referenceOutputFile\""
+  echo "cmd is \"$cmd\""
   echo "generate is $generate"
   echo "summary is $summary"
-  echo "valg is $valg"
+  echo "useValgrind is $useValgrind"
+  echo "expectedExitCode is $expectedExitCode"
+  echo "$matchErr is $matchErr"
 fi
 
+# This is where we actually run Frobby
+cat $inputFile|$frobby $action $params > $frobbyOut 2> $frobbyErr
+frobbyExitCode="$?"
 
-if [ $generate = 1 ]
+if [ $matchErr = 1 ];
 then
-  if [ "$inputFile" == "$referenceOutputFile" ];
+  # Use a new file to remove lines containing the words DEBUG
+  frobbyOut="$frobbyChangedErr";
+  sed /DEBUG/d < $frobbyErr > $frobbyOut
+fi
+
+# Check if Frobby's output matches the reference output file.
+diff $frobbyOut $referenceOutputFile > /dev/null 2> /dev/null
+referenceMatch="$?"
+
+if [ $generate = 1 ];
+then
+  if [ $frobbyExitCode != $expectedExitCode ];
   then
-    exit 0;
+    echo "Halting generation of output due to getting exit code $frobbyExitCode."
+    echo "The expected exit code was $expectedExitCode. This is for "
+	echo "  cat $inputFile|$frobby $action $params"
+    echo "Giving error output of "
+    cat $origFrobbyErr
+    exit 1
   fi
-  echo "***** Generating $referenceOutputFile";
-  cat $inputFile|$frobby $action $params > $referenceOutputFile;
+
+  cp -f $frobbyOut $referenceOutputFile;
+  if [ $referenceMatch = 0 ];
+  then
+    echo -n "g";
+  else
+    echo;
+    echo -n "Replaced output file $referenceOutputFile with new version.";
+  fi
   exit 0
 fi
 
-if [ $valg = 1 ];
+if [ $useValgrind = 1 ];
 then
-  errs=`cat $inputFile|valgrind $frobby $action $params 2>&1 |
-        grep -e "ERROR SUMMARY: [^0].* error" -e "--leak-check=full"`;
+  errs=`grep -e "ERROR SUMMARY: [^0].* error"
+             -e "--leak-check=full" $frobbyErr`;
   if [ "$errs" == "" ];
   then
     echo -n v
-    exit 0;
   else
     echo
     echo
     echo "valgrind reports issue on running:"
-    echo "  cat $inputFile|valgrind $frobby $action $params"
+    echo "  cat $inputFile|$frobby $action $params"
     echo "Re-running to show full details:"
     echo
-    cat $inputFile|valgrind --leak-check=full --show-reachable=yes $frobby $action $params;
+    cat $inputFile|valgrind --leak-check=full --show-reachable=yes $origFrobby $action $params;
     echo
     echo "Re-running to show limited details:"
-    cat $inputFile|valgrind --leak-check=full --show-reachable=no $frobby $action $params > /dev/null;
+    cat $inputFile|valgrind --leak-check=full --show-reachable=no $origFrobby $action $params > /dev/null;
     echo "This is a valgrind report on running:"
     echo "  cat $inputFile|valgrind $frobby $action $params"
     echo "Look further up for a run of valgrind with full details." 
@@ -126,10 +203,7 @@ then
   fi
 fi
 
-cat $inputFile|$frobby $action $params 2> /dev/null | \
-  diff - $referenceOutputFile > /dev/null
-
-if [ $? = 0 ];
+if [[ $referenceMatch = 0 && $frobbyExitCode = $expectedExitCode ]];
 then
   if [ $summary = 0 ];
   then
@@ -153,10 +227,16 @@ echo "***** Reference output:"
 cat $referenceOutputFile
 
 echo "***** Standard output from Frobby:"
-cat $inputFile|$frobby $action $params 2>/dev/null
+cat $origFrobbyOut
 
 echo "***** Error output from Frobby:"
-cat $inputFile|$frobby $action $params > /dev/null
+cat $origFrobbyErr
+
+echo "***** Exit code was $frobbyExitCode, and expecting $expectedExitCode"
+if [ $matchErr = 1 ];
+then
+   echo "***** Matching on error output, not standard output.";
+fi
 
 echo
 echo "***** A test $action: $inputFile -> $referenceOutputFile failed."
