remote changes

diff --git a/test/format/runtest b/test/format/runtest
--- a/test/format/runtest
+++ b/test/format/runtest
@@ -41,4 +41,26 @@ then
 fi
 
 
+
+
+../../$frobby format $2 $3 $4 $5 $6 $7 -iformat monos -oformat 4ti2 < $1 2> /dev/null| diff - $1.4ti2
+
+if [ $? != 0 ]
+then
+  echo
+  echo "Test $1 failed (monos to 4ti2)"
+  exit 1
+fi
+
+
+../../$frobby format $2 $3 $4 $5 $6 $7 -iformat 4ti2 -oformat monos < $1.4ti2 2> /dev/null| diff - $1.4ti2.monos
+
+if [ $? != 0 ]
+then
+  echo
+  echo "Test $1 failed (4ti2 to monos)"
+  exit 1
+fi
+
+
 echo -n .
